---
- name: This playbook help to learn Loops in ansible
  hosts: all

  vars:
   proxy_env:
   http_proxy: http://10.19.16.165:8080
  
  vars_files: 
       - contacts
 
  tasks:
   - name: this task helps to learn dictonary
     debug: msg= "{{item.value.name}}"s mobile is "{{item.value.mobile}}"
     with_dict: "{{contact_list}}"


   - name: this task helps to learn with_items list
     yum: name={{item}} state="present" update_cache="yes"
     environment: "{{ proxy_env }}" 
     with_items:
       - tree
       - vim
       - cscope
