---
 - name: install epel-release
   yum: name=epel-release state=present
   environment: "{{proxy_env}}"

 - name: Install nginx webserver on CentOS 
   yum: name=ngix stat=present
   environment: "{{proxy_env}}"
